const mongoose = require("mongoose");

const jobPostingSchema = new mongoose.Schema(
  {
    position: {
      type: String,
      required: true,
      maxLength: 100,
    },
    experience: {
      type: String,
      required: true,
      enum: [
        "ENTRY_LEVEL",
        "MID_SENIOR_LEVEL",
        "DIRECTOR",
        "EXECUTIVE",
        "NOT_APPLICABLE",
      ],
    },
    minExperience: {
      type: Number,
      // required: true,
      // default: 0,
    },
    maxExperience: {
      type: Number,
      // required: true,
      // default: 0,
    },
    salary: {
      type: String,
      required: true,
      enum: ["notSpecified", "specifyRange"],
    },
    minSalary: {
      type: Number,
      // required: true,
      // default: 0,
    },
    maxSalary: {
      type: Number,
      // required: true,
      // default: 0,
    },
    location: {
      type: String,
      required: true,
    },
    about: {
      type: String,
      required: true,
    },
    requirements: {
      type: String,
      required: true,
    },
    numOpenings: {
      type: Number,
      required: true,
    },
    department: {
      type: String,
      required: true,
    },
    employmentType: {
      type: String,
      required: true,
      enum: ["FULL_TIME", "PART_TIME", "INTERNSHIP", "CONTRACT"],
    },
    mandatorySkills: {
      type: [String],
      required: true,
      enum: [
        "JavaScript",
        "Python",
        "Java",
        "HTML",
        "CSS",
        "SQL",
        "React",
        "Node.js",
        "Angular",
        "TypeScript",
        "Vue.js",
        "C++",
        "C#",
        "PHP",
        "Swift",
        "Ruby",
        "MongoDB",
        "Firebase",
        "Django",
        "ASP.NET",
        "Express.js",
        "Spring",
        "Redux",
        "TensorFlow",
        "Kubernetes",
        "Docker",
        "Git",
        "HTML5",
        "CSS3",
        "Sass",
        "Less",
        "Bootstrap",
        "Tailwind CSS",
        "jQuery",
        "RESTful API",
        "GraphQL",
        "PostgreSQL",
        "MySQL",
        "Microsoft Azure",
        "Amazon Web Services (AWS)",
        "Google Cloud Platform (GCP)",
        "Linux",
        "Unix",
        "Shell Scripting",
        "JSON",
        "XML",
        "Webpack",
        "Babel",
        "Jenkins",
        "Continuous Integration/Continuous Deployment (CI/CD)",
      ],
    },
    technicalSkills: {
      type: [String],
      required: true,
      enum: [
        "JavaScript",
        "Python",
        "Java",
        "HTML",
        "CSS",
        "SQL",
        "React",
        "Node.js",
        "Angular",
        "TypeScript",
        "Vue.js",
        "C++",
        "C#",
        "PHP",
        "Swift",
        "Ruby",
        "MongoDB",
        "Firebase",
        "Django",
        "ASP.NET",
        "Express.js",
        "Spring",
        "Redux",
        "TensorFlow",
        "Kubernetes",
        "Docker",
        "Git",
        "HTML5",
        "CSS3",
        "Sass",
        "Less",
        "Bootstrap",
        "Tailwind CSS",
        "jQuery",
        "RESTful API",
        "GraphQL",
        "PostgreSQL",
        "MySQL",
        "Microsoft Azure",
        "Amazon Web Services (AWS)",
        "Google Cloud Platform (GCP)",
        "Linux",
        "Unix",
        "Shell Scripting",
        "JSON",
        "XML",
        "Webpack",
        "Babel",
        "Jenkins",
        "Continuous Integration/Continuous Deployment (CI/CD)",
      ],
    },
    numApplicants: {
      type: Number,
    },
    status: {
      type: String,
      required: true,
      enum: ["open", "closed"],
      default: "open",
    },
  },
  {
    timestamps: true,
  }
);

const JobPosting =
  mongoose.models.JobPosting || mongoose.model("JobPosting", jobPostingSchema);

module.exports = JobPosting;
